// <auto-generated />
using System;
using CvService.Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CvService.Repositories.Migrations
{
    [DbContext(typeof(CvContext))]
    partial class CvContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CvService.Repositories.Pocos.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Blurb");

                    b.Property<string>("CompanyName");

                    b.Property<int?>("CvId");

                    b.Property<DateTime?>("End");

                    b.Property<string>("Location");

                    b.Property<string>("Role");

                    b.Property<DateTime>("Start");

                    b.HasKey("Id");

                    b.HasIndex("CvId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CvService.Repositories.Pocos.Cv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Blurb");

                    b.Property<string>("Name");

                    b.Property<string>("TagLine");

                    b.HasKey("Id");

                    b.ToTable("Cvs");
                });

            modelBuilder.Entity("CvService.Repositories.Pocos.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Blurb");

                    b.Property<int?>("CvId");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.HasKey("Id");

                    b.HasIndex("CvId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("CvService.Repositories.Pocos.Company", b =>
                {
                    b.HasOne("CvService.Repositories.Pocos.Cv", "Cv")
                        .WithMany("Companies")
                        .HasForeignKey("CvId");
                });

            modelBuilder.Entity("CvService.Repositories.Pocos.Skill", b =>
                {
                    b.HasOne("CvService.Repositories.Pocos.Cv", "Cv")
                        .WithMany("Skills")
                        .HasForeignKey("CvId");
                });
#pragma warning restore 612, 618
        }
    }
}
